package io.github.mrelizeus.qwcie.domain;

public enum ObservedSignal {
    GROUP1_CHLORIDES_PRECIPITATED,
    POST_CHLORIDE_FILTRATE_CATIONS_REMAIN_IN_SOLUTION,
    ALKALINE_OXIDATIVE_TREATMENT_APPLIED,
    ALKALINE_SOLID_LIQUID_SPLIT_READY,
    ALKALINE_PRECIPITATE_ISOLATED,
    ALKALINE_PRECIPITATE_DISSOLVED_BY_HCL_HEAT,
    ALKALINE_SOLUTION_ISOLATED,
    SN2_OXIDIZED_TO_SN4,
    GROUP1_RESIDUE_READY,
    GROUP1_DISSOLVED_COMPLEXES_READY,
    HG_BLACK_RESIDUE,
    AG_DIAMMINE_COMPLEX_FORMED,
    AG_WHITE_AGCL_CONFIRMED,
    PB_YELLOW_PBCRO4_CONFIRMED,
    SB_LILAC_COMPLEX_CONFIRMED
}
