package io.github.mrelizeus.qwcie.domain;

public enum ReactionAction {
    ADD_DILUTE_HCL_OR_NACL,
    FILTER_POST_CHLORIDE_FILTRATE,
    ADD_EXCESS_NAOH_H2O2_WITH_HEAT,
    ADD_HCL_WITH_HEAT,
    SELECT_ALKALINE_PRECIPITATE_BRANCH,
    SELECT_ALKALINE_SOLUTION_BRANCH,
    ADD_CONCENTRATED_HCL,
    SELECT_RESIDUE_BRANCH,
    SELECT_DISSOLVED_BRANCH,
    ADD_EXCESS_NH4OH,
    ADD_HNO3,
    ADD_K2CRO4_WITH_ACETATE_BUFFER,
    ADD_HCL_KNO2_RHODAMINE_B
}
