package io.github.mrelizeus.qwcie.domain.protocol;

public enum ReactionAction {
    ADD_DILUTE_HCL_OR_NACL,
    FILTER_POST_CHLORIDE_FILTRATE,
    SELECT_POST_CHLORIDE_FILTRATE_BRANCH,
    SELECT_POST_CHLORIDE_PRECIPITATE_BRANCH,
    ADD_EXCESS_NAOH_H2O2_WITH_HEAT,
    ADD_HCL_WITH_HEAT,
    SELECT_ALKALINE_PRECIPITATE_BRANCH,
    SELECT_ALKALINE_SOLUTION_BRANCH,
    ADD_CONCENTRATED_HCL,
    SELECT_RESIDUE_BRANCH,
    SELECT_DISSOLVED_BRANCH,
    ADD_EXCESS_NH4OH,
    SELECT_HG_BLACK_RESIDUE_PRESENT_BRANCH,
    SELECT_HG_BLACK_RESIDUE_ABSENT_BRANCH,
    ADD_HNO3,
    SELECT_AGCL_PRECIPITATE_PRESENT_BRANCH,
    SELECT_AGCL_PRECIPITATE_ABSENT_BRANCH,
    ADD_K2CRO4_WITH_ACETATE_BUFFER,
    SELECT_PBCRO4_PRECIPITATE_PRESENT_BRANCH,
    SELECT_PBCRO4_PRECIPITATE_ABSENT_BRANCH,
    ADD_HCL_KNO2_RHODAMINE_B
}
