package io.github.mrelizeus.qwcie.domain;

public enum ObservedSignal {
    GROUP1_CHLORIDES_PRECIPITATED,
    GROUP1_RESIDUE_READY,
    GROUP1_DISSOLVED_COMPLEXES_READY,
    HG_BLACK_RESIDUE,
    AG_DIAMMINE_COMPLEX_FORMED,
    AG_WHITE_AGCL_CONFIRMED,
    PB_YELLOW_PBCRO4_CONFIRMED,
    SB_LILAC_COMPLEX_CONFIRMED
}
